### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by elluzion** [elluzion/elluzion.co#9]
- [x] kebab-case all component files for consistency
- [x] improve UI for analyzer (drag and drop)
- [ ] Don't have a drop-down for song downloads when there is only one entry (Radio Edit/Extended Mix)
- [ ] Direct download through Google Drive (URL PATTERN: https://drive.google.com/uc?export=download&id=FILEID)
- [ ] Page metadata

**Comment by elluzion** [comment]
Moved to project
